### ISSUE TITLE
Controlli di Correttezza AKA Cose da fare per la ELE

### ISSUE THREAD

**Issue by Aronoele20395** [UnipdSurvivors/TecWeb#54]
- [x] Controllare `<br />` doppi
- [x] tag alt
- [x] lettere accentate
- [x] status success e status failed in classi - MANCA SOLO IL CONTROLLO FINALE
- [x] pagina 404 (issue #34 ) - BASTA SCEGLIERE L'IMMAGINE DEFINITIVA
- [x] messaggi errore (css)
- [x] placeholder noleggio (js toolkit e html)
- [x] pulsante "Annulla"
- [x] istruzioni eliminazione prenotazioni/noleggi - REVISIONE FINALE (issue #29 )
- [x] longdesc (issue #53 )
- [x] titoli link e bottoni - modifica "value"(issue #56 )
- [x] stessi contatti nel footer e nella pagina dei contatti, potrebbe essere importante eleonora, non trovi?
- [x] controllo e riordino dei file (style generale!!!!!)

**Comment by Penaz91** [comment]
Riferimenti per 404: Issue #34

**Comment by Aronoele20395** [comment]
Ok ma non so se sarò in grado di fare tutto da sola per i 404

**Comment by Aronoele20395** [comment]
@Penaz91 per favore controlla che i messaggi di conferma/errore funzionino correttamente.

**Comment by Penaz91** [comment]
Gli status sembrano funzionare
